---
galaxy_info:
  role_name: example_httpd
  author: RHDP Content Team
  description: Example httpd site for RHEL Field Sourced Content
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - rhel
    - httpd
    - example
