---
# Example playbook for RHEL Field Asset.
# Inventory groups `bastions` and `nodes` are written by the platform.
# Extra vars include `guid` and `field_asset.*`.

- name: Example field sourced content
  hosts: nodes
  become: true
  roles:
    - example_setup
